name: Release Executables

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write
  statuses: write

on:
  push:
    tags:
      - v*

jobs:

  set-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Get the tag name
        id: tag
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build essentials
        run: |
          sudo apt-get update
          sudo apt-get install build-essential
        shell: bash

      - name: Build and Publish Executables (Linux)
        run: |
          make publish
          mkdir release
          mv JuulesPlusPlus release/
          zip -r -j "JuulesPlusPlus-${{ steps.tag.outputs.TAG_NAME }}-linux.zip" release/
        working-directory: .

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            JuulesPlusPlus-${{ steps.tag.outputs.TAG_NAME }}-linux.zip

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Publish Executables (Windows)
        run: |
          make publish
          7z a "JuulesPlusPlus-${{ steps.tag.outputs.TAG_NAME }}-windows-x64.zip" JuulesPlusPlus.exe
        shell: bash

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            JuulesPlusPlus-${{ steps.tag.outputs.TAG_NAME }}-windows-x64.zip
