name: Release Executables

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set tag
        run: |
          echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"

      - name: Install build essentials
        run: |
          sudo apt-get update
          sudo apt-get install build-essential
        shell: bash

      - name: Build and Publish Executables (Windows)
        run: |
          make publish
          mv JuulesPlusPlus JuulesPlusPlus.exe
          7z a "JuulesPlusPlus-$tag-windows-x64.zip" JuulesPlusPlus.exe
        shell: bash

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            JuulesPlusPlus-${{ env.tag }}-windows-x64.zip
