name: Release Executables

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write
  statuses: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Publish Executables (Windows)
        run: |
          make publish
          mv JuulesPlusPlus JuulesPlusPlus.exe
          7z a "JuulesPlusPlus-windows-x64.zip" JuulesPlusPlus.exe
        shell: bash

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            JuulesPlusPlus-windows-x64.zip
            JuulesPlusPlus-linux.zip